# generated by scripts/generate-formula.ts — do not edit by hand
class Tomtom < Formula
  desc "Unix-friendly CLI for TomTom's location APIs"
  homepage "https://github.com/daanrongen/tomtom"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/daanrongen/tomtom/releases/download/v0.1.0/tomtom-darwin-arm64.tar.gz"
      sha256 "a52a52e3c9e7895374b35e255d4ca3c81963357525c893e406c870826161a198"
    end
    on_intel do
      url "https://github.com/daanrongen/tomtom/releases/download/v0.1.0/tomtom-darwin-x64.tar.gz"
      sha256 "ce66816bc923f7095742560ffd6e26b59640ec6ad06bf2a8d49ef95b79fc3367"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/daanrongen/tomtom/releases/download/v0.1.0/tomtom-linux-arm64.tar.gz"
      sha256 "39d60c08dad96bdda1779abbd2fc4ab4dfda539e09118e7186ca96ad354466b3"
    end
    on_intel do
      url "https://github.com/daanrongen/tomtom/releases/download/v0.1.0/tomtom-linux-x64.tar.gz"
      sha256 "bd5236522046748fc2a369325052efbcd5b2348c956cc52c7586791caeb6e5a5"
    end
  end

  def install
    bin.install "tomtom"
  end

  test do
    system "#{bin}/tomtom", "--version"
  end
end
