# generated by scripts/generate-formula.ts — do not edit by hand
class Tomtom < Formula
  desc "Unix-friendly CLI for TomTom's location APIs"
  homepage "https://github.com/daanrongen/tomtom"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/daanrongen/tomtom/releases/download/v0.1.1/tomtom-darwin-arm64.tar.gz"
      sha256 "2c5ee9fb8864a567bf504e56a2a45bdedf9e7b6d77024e97ee34169924114c36"
    end
    on_intel do
      url "https://github.com/daanrongen/tomtom/releases/download/v0.1.1/tomtom-darwin-x64.tar.gz"
      sha256 "c90982a3014f7b1eaec8636ddf4c2bf62db50825175648fd6f15ac3507beb7e1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/daanrongen/tomtom/releases/download/v0.1.1/tomtom-linux-arm64.tar.gz"
      sha256 "7f358833e48530b37e46663b944a022cb29d727dcc7f354e64cd957f17964905"
    end
    on_intel do
      url "https://github.com/daanrongen/tomtom/releases/download/v0.1.1/tomtom-linux-x64.tar.gz"
      sha256 "824f7633a9c1869081694df9fea0dc082fdd536df8897f05646e87d341f80fa6"
    end
  end

  def install
    bin.install "tomtom"
  end

  test do
    system "#{bin}/tomtom", "--version"
  end
end
